//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Imagenes
    {
        public int Id { get; set; }
        public int JuegoId { get; set; }
        public string UrlImagenMiniatura { get; set; }
        public string UrlImagenMediana { get; set; }
        public bool EsPortada { get; set; }
    
        public virtual Juego Juego { get; set; }
    }
}
