//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Juego
    {
        public Juego()
        {
            this.Imagenes = new HashSet<Imagenes>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public int GeneroId { get; set; }
        public int ConsolaId { get; set; }
        public string VideoYoutube { get; set; }
        public bool Activo { get; set; }
    
        public virtual Consola Consola { get; set; }
        public virtual Genero Genero { get; set; }
        public virtual ICollection<Imagenes> Imagenes { get; set; }
    }
}
